### ISSUE TITLE
Standardize the Manager response Error output for 4xx responses

### ISSUE THREAD

**Issue by msawka** [OpenAperture/manager#12]
The manager's Controllers currently return a variety of response objects when errors occur. All requests set the content-type to application/json, but some return strings, some return json objects, some return json arrays. These should be standardized into a single error response object that the UI can easily parse. Something like:

{
"errors": [
{
"message": "what happened"
}
]
}

**Comment by TheFirstAvenger** [comment]
Fixed with https://github.com/OpenAperture/manager/pull/16
